"""add comment type to ticket comments

Revision ID: fc26bbab5f5f
Revises: 9169ace6f25f
Create Date: 2026-06-03 10:43:27.656973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc26bbab5f5f'
down_revision = '9169ace6f25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_type', sa.String(length=30), nullable=False))
        batch_op.create_index(batch_op.f('ix_ticket_comments_comment_type'), ['comment_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_comments_comment_type'))
        batch_op.drop_column('comment_type')

    # ### end Alembic commands ###
